### ISSUE TITLE
Timestamps in Pricing Data 

### ISSUE THREAD

**Issue by shaggoththebig444** [osmosis-labs/osmosis-info#23]
Hey guys,

I run in some inconsistencies with the data from the historical price endpoint. Maybe I miss sth (and please correct me then) but I wanted to point it out at least:

When I query the data for ATOM for 1643241600 (Thu Jan 27 2022 00:00:00 GMT+0000), it returns:

` {
    "time": 1643241600,
    "close": 32.61,
    "high": 36,
    "low": 32.19,
    "open": 35.97
  },`

with an open of the 27th of 35.97 and a close of 32.61. However, if I check both Coinmarketcap and the chart on your analytics page, the 27th opened at 32.sth (depending on the source) and not 35.97 (or close to that). 

Since the charting tool is correct, I assume you transform the api data somehow. Can you shortly explain why you do this? Thanks for the time.

Best,
SGB

**Comment by imperator-co** [comment]
Hi @shaggoththebig444 ,

Thanks for pointing this out! Actually, this is due to the OHLC script we are running everyday at 1AM UTC which shifts the data by 1 day
So the example you sent `{ "time": 1643241600, "close": 32.61, "high": 36, "low": 32.19, "open": 35.97 },` should represent Jan 26 2022 instead of Jan 27 2022

We will deploy a fix ASAP
