### ISSUE TITLE
IBC transfers past 24 hrs

### ISSUE THREAD

**Issue by IbrarMakaveli** [osmosis-labs/osmosis-info#7]
# IBC transfers past 24 hrs on each :
https://info.osmosis.zone/token/OSMO

**Comment by jblbit** [comment]
Hi @IbrarMakaveli , I'm an data infra engineer and would really love to help contribute to Osmosis, maybe starting with the info page since it's related to my background.

Do you have some small features that I can start with, or shall I try this one? Would appreciate some pointers and more details of this feature
